version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
      target: auth
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
      - user-grpc


  user:
    build:
      context: .
      dockerfile: Dockerfile
      target: user
    env_file:
      - .env
    ports:
      - '3001:3001'
    depends_on:
      - db

  user-grpc:
    build:
      context: .
      dockerfile: Dockerfile
      target: user-grpc
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: template-db
    image: mariadb:11.6.2
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  dbdata:

networks:
  default:
    name: nest-microservices
