// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: proto/user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface Empty {
}

export interface FindOneUserDto {
  id: string;
}

export interface PaginationDto {
  page: number;
  skip: number;
}

export interface Users {
  users: User[];
}

export interface User {
  id: string;
  username: string;
  password: string;
  age: number;
  subscribed: boolean;
  socialMedia: SocialMedia | undefined;
}

export interface SocialMedia {
  twitterUri?: string | undefined;
  facebookUri?: string | undefined;
}

export interface FindOrCreateUserRequest {
  googleId: string;
  email: string;
  name: string;
}

export interface UserResponse {
  id: string;
  googleId: string;
  email: string;
  name: string;
  /** ACTIVE, DELETED, ... */
  status: string;
}

export interface SoftDeleteUserRequest {
  userId: string;
}

export interface SoftDeleteUserResponse {
  success: boolean;
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  findOrCreateUser(request: FindOrCreateUserRequest): Observable<UserResponse>;

  softDeleteUser(request: SoftDeleteUserRequest): Observable<SoftDeleteUserResponse>;

  findAllUsers(request: Empty): Observable<Users>;

  findOneUser(request: FindOneUserDto): Observable<User>;

  queryUsers(request: Observable<PaginationDto>): Observable<Users>;
}

export interface UserServiceController {
  findOrCreateUser(request: FindOrCreateUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  softDeleteUser(
    request: SoftDeleteUserRequest,
  ): Promise<SoftDeleteUserResponse> | Observable<SoftDeleteUserResponse> | SoftDeleteUserResponse;

  findAllUsers(request: Empty): Promise<Users> | Observable<Users> | Users;

  findOneUser(request: FindOneUserDto): Promise<User> | Observable<User> | User;

  queryUsers(request: Observable<PaginationDto>): Observable<Users>;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["findOrCreateUser", "softDeleteUser", "findAllUsers", "findOneUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = ["queryUsers"];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
